In [1]:
from __future__ import absolute_import, division, print_function, unicode_literals
import tensorflow as tf

In [ ]:
#Once you have run this on your own system, you can try it on colab here:

# https://www.tensorflow.org/tutorials/quickstart/beginner

In [2]:
mnist = tf.keras.datasets.mnist

(x_train, y_train), (x_test, y_test) = mnist.load_data()
x_train, x_test = x_train / 255.0, x_test / 255.0


11493376/11490434 [==============================] - 2s 0us/step


In [3]:
model = tf.keras.models.Sequential([
  tf.keras.layers.Flatten(input_shape=(28, 28)),
  tf.keras.layers.Dense(128, activation='relu'),
  tf.keras.layers.Dropout(0.2),
  tf.keras.layers.Dense(10)
])


In [4]:
predictions = model(x_train[:1]).numpy()
predictions


If you intended to run this layer in float32, you can safely ignore this warning. If in doubt, this warning is likely only an issue if you are porting a TensorFlow 1.X model to TensorFlow 2.

To change all layers to have dtype float64 by default, call `tf.keras.backend.set_floatx('float64')`. To change just this layer, pass dtype='float64' to the layer constructor. If you are the author of this layer, you can disable autocasting by passing autocast=False to the base Layer constructor.



array([[-0.26006317,  0.25909358, -0.3262072 , -1.0986954 , -0.37990165,
         0.42271674,  0.16937692,  0.5080466 ,  0.52860975,  0.07399145]],
      dtype=float32)

In [5]:
tf.nn.softmax(predictions).numpy()


array([[0.07040011, 0.11831512, 0.06589423, 0.03043407, 0.06244938,
        0.13934804, 0.10816251, 0.15176065, 0.15491363, 0.09832216]],
      dtype=float32)

In [6]:
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)


In [7]:
loss_fn(y_train[:1], predictions).numpy()


1.9707805

In [8]:
model.compile(optimizer='adam',
              loss=loss_fn,
              metrics=['accuracy'])


In [9]:
model.fit(x_train, y_train, epochs=5)


Train on 60000 samples
Epoch 1/5
60000/60000 [==============================] - 11s 186us/sample - loss: 0.2964 - accuracy: 0.9138
Epoch 2/5
60000/60000 [==============================] - 10s 165us/sample - loss: 0.1449 - accuracy: 0.9572
Epoch 3/5
60000/60000 [==============================] - 11s 176us/sample - loss: 0.1082 - accuracy: 0.9673
Epoch 4/5
60000/60000 [==============================] - 12s 193us/sample - loss: 0.0896 - accuracy: 0.9734
Epoch 5/5
60000/60000 [==============================] - 11s 188us/sample - loss: 0.0761 - accuracy: 0.9759


In [10]:
probability_model = tf.keras.Sequential([
  model,
  tf.keras.layers.Softmax()
])


In [11]:
probability_model(x_test[:5])



<tf.Tensor: id=28930, shape=(5, 10), dtype=float32, numpy=
array([[1.4386394e-07, 5.7946656e-09, 2.8164510e-05, 6.9176150e-04,
        1.5114052e-11, 3.3754858e-07, 1.7800275e-12, 9.9922931e-01,
        2.3037446e-06, 4.7944726e-05],
       [3.3329261e-08, 9.6743670e-06, 9.9997830e-01, 1.0759660e-05,
        1.4783500e-13, 1.1619047e-06, 1.3367460e-08, 2.4284463e-12,
        7.5053094e-08, 5.8004572e-13],
       [6.8652344e-07, 9.9940240e-01, 7.8378856e-05, 7.7887580e-07,
        4.3291682e-05, 1.9373160e-06, 7.0406545e-06, 4.0802374e-04,
        5.4616794e-05, 2.9399987e-06],
       [9.9899071e-01, 3.3511680e-09, 1.1223997e-04, 1.6830448e-07,
        2.5999258e-05, 9.5435316e-05, 6.9950440e-04, 1.1674456e-05,
        1.0289822e-06, 6.3247804e-05],
       [1.0024964e-06, 2.3800128e-08, 1.3229251e-05, 4.2359748e-08,
        9.7413039e-01, 9.1933998e-07, 8.5641705e-06, 7.4903364e-05,
        5.9923118e-06, 2.5764825e-02]], dtype=float32)>