In [1]:
from __future__ import absolute_import, division, print_function, unicode_literals
import tensorflow as tf

In [2]:
#Once you have run this on your own system, you can try it on colab here:

# https://www.tensorflow.org/tutorials/quickstart/beginner

In [3]:
mnist = tf.keras.datasets.mnist

(x_train, y_train), (x_test, y_test) = mnist.load_data()
x_train, x_test = x_train / 255.0, x_test / 255.0


In [4]:
model = tf.keras.models.Sequential([
  tf.keras.layers.Flatten(input_shape=(28, 28)),
  tf.keras.layers.Dense(128, activation='relu'),
  tf.keras.layers.Dropout(0.2),
  tf.keras.layers.Dense(10)
])


In [5]:
predictions = model(x_train[:1]).numpy()
predictions

array([[-0.19896734,  0.1846184 ,  0.6152543 ,  0.98006797,  0.06164537,
        -0.9810164 ,  0.13198064, -0.02699777,  0.5831794 ,  0.4314483 ]],
      dtype=float32)

In [6]:
tf.nn.softmax(predictions).numpy()


array([[0.06106548, 0.08961587, 0.1378503 , 0.19853829, 0.07924619,
        0.02793548, 0.08502069, 0.07252391, 0.13349892, 0.11470485]],
      dtype=float32)

In [7]:
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)


In [8]:
loss_fn(y_train[:1], predictions).numpy()


3.5778577

In [9]:
model.compile(optimizer='adam',
              loss=loss_fn,
              metrics=['accuracy'])


In [10]:
model.fit(x_train, y_train, epochs=5)


Epoch 1/5
1875/1875 [==============================] - 2s 758us/step - loss: 0.4745 - accuracy: 0.8643
Epoch 2/5
1875/1875 [==============================] - 1s 724us/step - loss: 0.1497 - accuracy: 0.9561
Epoch 3/5
1875/1875 [==============================] - 1s 705us/step - loss: 0.1113 - accuracy: 0.9669
Epoch 4/5
1875/1875 [==============================] - 1s 713us/step - loss: 0.0859 - accuracy: 0.9727
Epoch 5/5
1875/1875 [==============================] - 2s 851us/step - loss: 0.0731 - accuracy: 0.9777


In [13]:
probability_model = tf.keras.Sequential([
  model,
  tf.keras.layers.Softmax()
])


In [26]:
probability_model(x_test[:5])



<tf.Tensor: shape=(5, 10), dtype=float32, numpy=
array([[2.25379517e-06, 1.15012011e-09, 1.16813112e-06, 1.00628939e-03,
        2.24751554e-11, 4.91404944e-06, 1.18941413e-12, 9.98968005e-01,
        7.21695983e-08, 1.73689641e-05],
       [2.46016452e-08, 1.93348955e-04, 9.99698639e-01, 1.07635839e-04,
        2.53527515e-14, 1.02174816e-07, 7.09652603e-09, 3.07971449e-13,
        3.91604402e-07, 5.63738407e-14],
       [7.84472832e-07, 9.99286354e-01, 1.83995915e-04, 1.97620029e-05,
        3.31464216e-05, 1.41024857e-05, 1.33529074e-05, 3.58567166e-04,
        8.73545141e-05, 2.54576275e-06],
       [9.99993801e-01, 6.04293227e-10, 1.35278094e-06, 3.90624763e-07,
        3.69299991e-09, 2.85240822e-06, 4.74275197e-07, 9.06462787e-07,
        8.29714630e-10, 2.03331396e-07],
       [1.28587417e-05, 4.22954685e-08, 9.09621394e-06, 4.81437255e-08,
        9.99239564e-01, 3.27581438e-06, 1.63240711e-05, 8.99121733e-06,
        4.84566556e-07, 7.09350512e-04]], dtype=float32)>