In [2]:
from __future__ import absolute_import, division, print_function, unicode_literals
import tensorflow as tf

In [ ]:
#Once you have run this on your own system, you can try it on colab here:

# https://www.tensorflow.org/tutorials/quickstart/beginner

In [4]:
mnist = tf.keras.datasets.mnist

(x_train, y_train), (x_test, y_test) = mnist.load_data()
x_train, x_test = x_train / 255.0, x_test / 255.0


In [6]:
model = tf.keras.models.Sequential([
  tf.keras.layers.Flatten(input_shape=(28, 28)),
  tf.keras.layers.Dense(128, activation='relu'),
  tf.keras.layers.Dropout(0.2),
  tf.keras.layers.Dense(10)
])


In [7]:
predictions = model(x_train[:1]).numpy()
predictions

array([[-0.01169006,  0.8188598 , -0.6778507 , -0.21059465,  0.22232586,
         1.051267  ,  0.2521963 ,  0.27271193,  0.05793881, -0.12436652]],
      dtype=float32)

In [8]:
tf.nn.softmax(predictions).numpy()


array([[0.07472186, 0.17145528, 0.0383829 , 0.06124413, 0.09442336,
        0.2163137 , 0.09728638, 0.09930288, 0.08011006, 0.06675947]],
      dtype=float32)

In [9]:
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)


In [10]:
loss_fn(y_train[:1], predictions).numpy()


1.5310256

In [11]:
model.compile(optimizer='adam',
              loss=loss_fn,
              metrics=['accuracy'])


In [12]:
model.fit(x_train, y_train, epochs=5)


Epoch 1/5
1875/1875 [==============================] - 2s 1ms/step - loss: 0.4843 - accuracy: 0.8572
Epoch 2/5
1875/1875 [==============================] - 2s 1ms/step - loss: 0.1538 - accuracy: 0.9532
Epoch 3/5
1875/1875 [==============================] - 2s 932us/step - loss: 0.1080 - accuracy: 0.9670
Epoch 4/5
1875/1875 [==============================] - 2s 987us/step - loss: 0.0859 - accuracy: 0.9727
Epoch 5/5
1875/1875 [==============================] - 2s 998us/step - loss: 0.0720 - accuracy: 0.9769


In [14]:
probability_model = tf.keras.Sequential([
  model,
  tf.keras.layers.Softmax()
])


In [15]:
probability_model(x_test[:5])



<tf.Tensor: shape=(5, 10), dtype=float32, numpy=
array([[3.06697379e-09, 1.25097613e-10, 1.73226539e-07, 3.84783089e-05,
        2.27611528e-12, 7.24834095e-08, 4.40363327e-12, 9.99960780e-01,
        6.25444656e-08, 4.47191695e-07],
       [1.19449375e-08, 1.82927673e-04, 9.99807179e-01, 9.76683350e-06,
        5.13484708e-13, 5.04496178e-09, 1.15184617e-09, 8.91006697e-14,
        7.27618925e-08, 1.99115399e-12],
       [1.13520434e-06, 9.99081016e-01, 1.30658111e-04, 5.74507658e-06,
        1.56811184e-05, 1.34911425e-05, 4.19495427e-06, 6.59380516e-04,
        8.73861354e-05, 1.30810588e-06],
       [9.99976277e-01, 1.51435156e-10, 3.41536776e-07, 1.13409918e-07,
        1.38094961e-07, 1.21361256e-06, 9.90296576e-06, 4.47004413e-06,
        1.19463536e-10, 7.47412378e-06],
       [3.53092873e-05, 1.48789384e-10, 2.13181397e-06, 3.79921268e-08,
        9.89995956e-01, 1.00335058e-07, 4.97326391e-06, 1.58842027e-04,
        3.94079393e-07, 9.80236661e-03]], dtype=float32)>