In [1]:
from __future__ import absolute_import, division, print_function, unicode_literals
import tensorflow as tf

In [ ]:
#Once you have run this on your own system, you can try it on colab here:

# https://www.tensorflow.org/tutorials/quickstart/beginner

In [2]:
mnist = tf.keras.datasets.mnist

(x_train, y_train), (x_test, y_test) = mnist.load_data()
x_train, x_test = x_train / 255.0, x_test / 255.0


In [3]:
model = tf.keras.models.Sequential([
  tf.keras.layers.Flatten(input_shape=(28, 28)),
  tf.keras.layers.Dense(128, activation='relu'),
  tf.keras.layers.Dropout(0.2),
  tf.keras.layers.Dense(10)
])


In [4]:
predictions = model(x_train[:1]).numpy()
predictions


If you intended to run this layer in float32, you can safely ignore this warning. If in doubt, this warning is likely only an issue if you are porting a TensorFlow 1.X model to TensorFlow 2.

To change all layers to have dtype float64 by default, call `tf.keras.backend.set_floatx('float64')`. To change just this layer, pass dtype='float64' to the layer constructor. If you are the author of this layer, you can disable autocasting by passing autocast=False to the base Layer constructor.



array([[-0.17971106, -0.44741535,  0.56500703,  0.52296555, -0.4170183 ,
        -0.24982934,  0.24240784,  0.16921325, -0.40630335,  0.45173526]],
      dtype=float32)

In [5]:
tf.nn.softmax(predictions).numpy()


array([[0.07557739, 0.05782684, 0.15915447, 0.15260209, 0.05961158,
        0.07045956, 0.11526988, 0.10713412, 0.06025376, 0.14211029]],
      dtype=float32)

In [6]:
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)


In [7]:
loss_fn(y_train[:1], predictions).numpy()


2.6527164

In [8]:
model.compile(optimizer='adam',
              loss=loss_fn,
              metrics=['accuracy'])


In [9]:
model.fit(x_train, y_train, epochs=5)


Train on 60000 samples
Epoch 1/5
60000/60000 [==============================] - 2s 38us/sample - loss: 0.2979 - accuracy: 0.9127
Epoch 2/5
60000/60000 [==============================] - 2s 33us/sample - loss: 0.1412 - accuracy: 0.9575
Epoch 3/5
60000/60000 [==============================] - 2s 33us/sample - loss: 0.1042 - accuracy: 0.9688
Epoch 4/5
60000/60000 [==============================] - 2s 33us/sample - loss: 0.0860 - accuracy: 0.9732
Epoch 5/5
60000/60000 [==============================] - 2s 33us/sample - loss: 0.0728 - accuracy: 0.9770


In [10]:
probability_model = tf.keras.Sequential([
  model,
  tf.keras.layers.Softmax()
])


In [11]:
probability_model(x_test[:5])



<tf.Tensor: id=28932, shape=(5, 10), dtype=float32, numpy=
array([[9.3152039e-08, 6.9390196e-09, 2.4315083e-05, 1.0187447e-03,
        2.5674079e-11, 2.6872178e-07, 1.6750848e-12, 9.9895608e-01,
        1.3704705e-07, 2.8140695e-07],
       [2.5510813e-08, 2.6711149e-04, 9.9962604e-01, 8.6282344e-05,
        5.5985533e-13, 1.8801571e-05, 3.5682925e-07, 7.9925297e-13,
        1.2547076e-06, 4.7038609e-11],
       [3.2411720e-07, 9.9888009e-01, 1.5300515e-04, 3.6397701e-06,
        1.0142791e-04, 1.0117585e-06, 5.5430650e-05, 6.4498966e-04,
        1.5967202e-04, 3.7912011e-07],
       [9.9991333e-01, 6.3872335e-10, 3.0190346e-05, 9.2974574e-08,
        2.0582732e-08, 5.6250938e-06, 2.2047561e-06, 3.9870414e-05,
        1.9831026e-08, 8.7095150e-06],
       [1.6456890e-07, 5.3574845e-10, 5.7752595e-06, 5.6556453e-09,
        9.9785125e-01, 5.2126428e-08, 4.2272850e-06, 1.5817912e-05,
        1.0049759e-07, 2.1226532e-03]], dtype=float32)>