In [1]:
from __future__ import absolute_import, division, print_function, unicode_literals
import tensorflow as tf

In [ ]:
#Once you have run this on your own system, you can try it on colab here:

# https://www.tensorflow.org/tutorials/quickstart/beginner

In [2]:
mnist = tf.keras.datasets.mnist

(x_train, y_train), (x_test, y_test) = mnist.load_data()
x_train, x_test = x_train / 255.0, x_test / 255.0


11493376/11490434 [==============================] - 2s 0us/step


In [3]:
model = tf.keras.models.Sequential([
  tf.keras.layers.Flatten(input_shape=(28, 28)),
  tf.keras.layers.Dense(128, activation='relu'),
  tf.keras.layers.Dropout(0.2),
  tf.keras.layers.Dense(10)
])


In [4]:
predictions = model(x_train[:1]).numpy()
predictions

array([[ 0.03228246, -0.04651786, -0.3823474 ,  0.826972  , -0.14200763,
        -0.8211063 , -0.7201964 ,  0.16972995, -0.12236664,  0.0992641 ]],
      dtype=float32)

In [5]:
tf.nn.softmax(predictions).numpy()


array([[0.10406786, 0.09618206, 0.06874564, 0.2303806 , 0.08742253,
        0.04432968, 0.04903647, 0.11940136, 0.08915657, 0.11127724]],
      dtype=float32)

In [6]:
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)


In [7]:
loss_fn(y_train[:1], predictions).numpy()


3.1161008

In [8]:
model.compile(optimizer='adam',
              loss=loss_fn,
              metrics=['accuracy'])


In [9]:
model.fit(x_train, y_train, epochs=5)


Epoch 1/5
1875/1875 [==============================] - 2s 846us/step - loss: 0.4713 - accuracy: 0.8648
Epoch 2/5
1875/1875 [==============================] - 1s 642us/step - loss: 0.1503 - accuracy: 0.9545
Epoch 3/5
1875/1875 [==============================] - 1s 640us/step - loss: 0.1044 - accuracy: 0.9685
Epoch 4/5
1875/1875 [==============================] - 1s 638us/step - loss: 0.0847 - accuracy: 0.9735
Epoch 5/5
1875/1875 [==============================] - 1s 649us/step - loss: 0.0710 - accuracy: 0.9780


In [10]:
probability_model = tf.keras.Sequential([
  model,
  tf.keras.layers.Softmax()
])


In [13]:
probability_model(x_test[:5])



<tf.Tensor: shape=(5, 10), dtype=float32, numpy=
array([[4.7451000e-08, 1.7674037e-09, 7.5609059e-06, 5.9421243e-05,
        2.3379819e-11, 2.0368104e-07, 3.1450032e-13, 9.9992847e-01,
        9.6958388e-08, 4.1372500e-06],
       [2.0220593e-06, 2.2830423e-04, 9.9974912e-01, 8.7645994e-06,
        2.6479340e-13, 5.0299832e-07, 1.8371054e-06, 4.3075616e-11,
        9.5204350e-06, 5.9183344e-13],
       [1.6732875e-07, 9.9874806e-01, 8.7851273e-05, 1.3476605e-05,
        3.6144511e-06, 2.3976375e-07, 3.9143379e-06, 7.6625316e-04,
        3.7527361e-04, 1.0485860e-06],
       [9.9976116e-01, 2.3152359e-11, 7.9657293e-05, 2.4513682e-07,
        4.3991392e-07, 7.4804802e-06, 1.1532503e-04, 3.4595178e-06,
        1.7209049e-07, 3.2013060e-05],
       [4.2788347e-06, 1.1009142e-09, 3.4432836e-05, 1.0188660e-07,
        9.8247415e-01, 1.6765875e-06, 2.9848925e-06, 7.2790950e-05,
        2.7453075e-06, 1.7406765e-02]], dtype=float32)>